//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiTest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblStudentDetail
    {
        public int StudentId { get; set; }
        public string StudentFirstName { get; set; }
        public string StudentLastName { get; set; }
        public string DateOfBirth { get; set; }
        public string DateOfJoining { get; set; }
        public string Class { get; set; }
        public string Section { get; set; }
        public string FatherName { get; set; }
        public string MotherName { get; set; }
    }
}
